app = 'gpdf2'
primary_region = 'fra'

[build]

# Web sunucusu süreci (Flask/Gunicorn)
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['web'] # 'web' sürecini kullanacağını belirt

[[vm]]
  memory = '2gb' # Belleği 2gb'a çıkardık
  cpu_kind = 'shared'
  cpus = 1

# Sağlık kontrolü tanımları
[[checks]]
  type = "http"
  name = "http-check"
  port = 8080
  path = "/"
  interval = "10s"
  timeout = "2s"
  grace_period = "5s"

# Birden fazla süreci tanımlamak için [processes] bölümü
[processes]
  web = "gunicorn -b 0.0.0.0:8080 --timeout 120 --access-logfile - --error-logfile - --log-level info backend.app:app"
  worker = "celery -A backend.celery_worker worker --loglevel=info --concurrency=1" # Tek worker ile başla
